import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTypescript,
  globalIgnores([
    ".next/**",
    ".paperpilot-pages/**",
    "node_modules/**",
    "out/**",
    // Generated by withWorkflow(). The package installs its own nested
    // .gitignore, but ESLint does not use nested Git ignore files.
    "src/app/.well-known/workflow/**",
  ]),
]);

export default eslintConfig;
