export type {
  CitationLibraryListRequest,
  CitationLibraryListResponse,
  CitationLibraryProvider,
  CitationLibrarySaveRequest,
  CitationLibrarySaveResponse,
  EvidenceNoteDraft,
  EvidenceQueryRequest,
  EvidenceQueryResponse,
  EvidenceRecord,
  EvidenceSaveRequest,
  EvidenceSaveResponse,
  EvidenceStore,
  IntegrationTransport,
  LiteratureSearchFilters,
  LiteratureSearchHit,
  LiteratureSearchProvider,
  LiteratureSearchRequest,
  LiteratureSearchResponse,
  NotesListRequest,
  NotesListResponse,
  NotesProvider,
  NotesSaveRequest,
  NotesSaveResponse,
  PaperSourceProvider,
  PaperSourceRequest,
  PaperSourceResponse,
  ProviderDescriptor,
  ProviderResponseMeta,
  ResearchToolRegistration,
  ResearchToolRegistry,
  ToolGovernancePolicy,
} from "./contracts";

export {
  WEB_EVIDENCE_CAPTURE_INPUT_SCHEMA,
  WEB_EVIDENCE_CAPTURE_SCHEMA_VERSION,
  WEB_EVIDENCE_CAPTURE_TOOL_NAME,
  WEB_EVIDENCE_CONTRACT_TOOL_NAME,
} from "./web-evidence-contract";

export type {
  WebEvidenceAgentAssertionV1,
  WebEvidenceAgentProposalV1,
  WebEvidenceArtifactV1,
  WebEvidenceCaptureEnvelopeV1,
  WebEvidenceCaptureMethod,
  WebEvidenceConfidence,
  WebEvidenceFragmentV1,
  WebEvidenceFragmentDerivationV1,
  WebEvidenceJsonValue,
  WebEvidenceLocatorV1,
  WebEvidenceSourceToolV1,
  WebEvidenceSourceV1,
  WebEvidenceTextPositionSelectorV1,
  WebEvidenceTextQuoteSelectorV1,
} from "./web-evidence-contract";

export {
  WEB_EVIDENCE_CAPTURE_TOOL_ANNOTATIONS,
  WEB_EVIDENCE_CONTRACT_INPUT_SCHEMA,
  WEB_EVIDENCE_CONTRACT_TOOL_ANNOTATIONS,
  detectPaperPilotWebMcpCapability,
  paperPilotWebEvidenceToolDefinitions,
  registerPaperPilotWebEvidenceTools,
} from "./web-evidence-browser-adapter";

export type {
  PaperPilotWebEvidenceToolCallbacks,
  PaperPilotWebMcpCapability,
  PaperPilotWebMcpDocument,
  PaperPilotWebMcpExecutionContext,
  PaperPilotWebMcpModelContext,
  PaperPilotWebMcpRegistration,
  PaperPilotWebMcpToolDefinition,
  RegisterPaperPilotWebEvidenceToolsOptions,
} from "./web-evidence-browser-adapter";

export {
  MockCitationLibraryProvider,
  MockEvidenceStore,
  MockLiteratureSearchProvider,
  MockNotesProvider,
  MockPaperSourceProvider,
  MockResearchToolRegistry,
  mockResearchToolRegistry,
  mockResearchTools,
} from "./mock-adapters";

export {
  ZOTERO_ATTACHMENT_ELIGIBILITIES,
  ZOTERO_ATTACHMENT_FAILURE_CODES,
  ZOTERO_ATTACHMENT_IMPORT_STATUSES,
  ZOTERO_ATTACHMENT_POLICY_MODES,
  ZOTERO_SCOPE_PROFILES,
  ZOTERO_ATTENTION_CODES,
  ZOTERO_CONNECTION_STATUSES,
  ZOTERO_SYNC_ERROR_CODES,
  ZOTERO_SYNC_RUN_STATUSES,
  isZoteroAttachmentImportCurrent,
  isWorkspaceIntegrationManager,
  parseZoteroAttachmentImportResponse,
  parseZoteroAttachmentListResponse,
  parseZoteroAttachmentPolicyResponse,
  parseZoteroAttachmentPolicyUpdateResponse,
  parseZoteroConnectionsResponse,
  parseZoteroDisconnectResponse,
  parseZoteroLibraryDiscoveryResponse,
  parseZoteroLibrarySelectionResponse,
  parseZoteroOAuthStartResponse,
  parseZoteroSyncRunsResponse,
  safeApiProblemMessage,
  trustedZoteroAuthorizationUrl,
  zoteroAttachmentImportsRoute,
  zoteroAttachmentPolicyRoute,
  zoteroAttachmentsRoute,
  zoteroCallbackConsumption,
  zoteroConnectionsRoute,
  zoteroDisconnectRoute,
  zoteroLibraryDiscoveryRoute,
  zoteroLibrarySelectionRoute,
  zoteroOAuthStartRoute,
  zoteroSyncRunsRoute,
} from "./zotero-ui";

export type {
  ZoteroAttachmentEligibility,
  ZoteroAttachmentFailureCode,
  ZoteroAttachmentImportStatus,
  ZoteroAttachmentImportUiResponse,
  ZoteroAttachmentImportUiSummary,
  ZoteroAttachmentListUiQuery,
  ZoteroAttachmentListUiResponse,
  ZoteroAttachmentPolicyMode,
  ZoteroAttachmentPolicyUiSummary,
  ZoteroAttachmentPolicyUpdateUiResponse,
  ZoteroAttachmentUiSummary,
  ZoteroAttentionCode,
  ZoteroCallbackConsumption,
  ZoteroConnectionStatus,
  ZoteroConnectionUiSummary,
  ZoteroConnectionsUiResponse,
  ZoteroLibraryDiscoveryUiResponse,
  ZoteroLibrarySelectionUiResponse,
  ZoteroLibraryUiSummary,
  ZoteroOAuthStartUiResponse,
  ZoteroScopeProfile,
  ZoteroSyncErrorCode,
  ZoteroSyncRunStatus,
  ZoteroSyncRunsUiResponse,
  ZoteroSyncRunUiSummary,
} from "./zotero-ui";
