import "server-only";

export { ZoteroReadOnlyAdapter } from "./adapter";
export type { ZoteroReadOnlyAdapterOptions } from "./adapter";
export {
  ZOTERO_API_VERSION,
  ZOTERO_MAX_KEY_BATCH_SIZE,
  ZOTERO_MAX_PAGE_SIZE,
} from "./contracts";
export type {
  ZoteroCollection,
  ZoteroCollectionBatchRequest,
  ZoteroConditionalResponse,
  ZoteroConnectionRequest,
  ZoteroCredentialLookup,
  ZoteroCredentialResolver,
  ZoteroDeletedObjects,
  ZoteroGroup,
  ZoteroGroupEditing,
  ZoteroGroupFileEditing,
  ZoteroGroupLibraryReading,
  ZoteroGroupType,
  ZoteroIdentity,
  ZoteroItem,
  ZoteroItemBatchRequest,
  ZoteroLibraryKind,
  ZoteroLibraryRef,
  ZoteroLibraryVersionRequest,
  ZoteroListItemsRequest,
  ZoteroListUserGroupsRequest,
  ZoteroNotModifiedResponse,
  ZoteroReadOnlyClient,
  ZoteroResolvedCredential,
  ZoteroResponse,
  ZoteroResponseMeta,
  ZoteroVersion,
  ZoteroVersionManifest,
} from "./contracts";
export { ZoteroAdapterError } from "./errors";
export type { ZoteroAdapterErrorCode } from "./errors";
export {
  ZOTERO_OAUTH_ACCESS_TOKEN_URL,
  ZOTERO_OAUTH_AUTHORIZE_URL,
  ZOTERO_OAUTH_ORIGIN,
  ZOTERO_OAUTH_REQUEST_TOKEN_URL,
  ZoteroOAuthClient,
  ZoteroOAuthError,
  assertZoteroOAuthProviderUrl,
  buildOAuthAuthorizationHeader,
  buildOAuthBaseStringUri,
  buildOAuthSignatureBaseString,
  buildZoteroAuthorizationUrl,
  createOAuthHmacSha1Signature,
  normalizeOAuthParameters,
  oauthPercentEncode,
  signOAuthRequest,
} from "./oauth";
export type {
  AccessTokenExchangeInput,
  OAuthParameter,
  OAuthSignatureBaseStringInput,
  SignOAuthRequestInput,
  ZoteroAllGroupsAccess,
  ZoteroAuthorizationOptions,
  ZoteroOAuthAccessCredentials,
  ZoteroOAuthClientOptions,
  ZoteroOAuthErrorCode,
  ZoteroOAuthErrorOptions,
  ZoteroOAuthRequestCredentials,
} from "./oauth";
export { ZoteroOAuthStateCodec } from "./oauth-state";
export type {
  IssuedZoteroOAuthState,
  ZoteroOAuthStateClaims,
  ZoteroOAuthStateCodecOptions,
  ZoteroOAuthStateSubject,
} from "./oauth-state";
export {
  ZOTERO_API_ORIGIN,
  assertZoteroApiUrl,
  assertZoteroGroupNextPageUrl,
  buildZoteroCurrentIdentityUrl,
  buildZoteroLibraryCollectionBatchUrl,
  buildZoteroLibraryCollectionVersionsUrl,
  buildZoteroLibraryDeletedUrl,
  buildZoteroLibraryItemBatchUrl,
  buildZoteroLibraryItemsUrl,
  buildZoteroLibraryItemVersionsUrl,
  buildZoteroRequestHeaders,
  buildZoteroUserGroupsUrl,
  chunkZoteroCollectionKeys,
  chunkZoteroItemKeys,
  normalizeZoteroCollectionKey,
  normalizeZoteroCollectionKeys,
  normalizeZoteroItemKey,
  normalizeZoteroItemKeys,
  normalizeZoteroLibraryId,
  normalizeZoteroObjectKey,
  parseZoteroNextLink,
  parseZoteroResponseHeaders,
  toZoteroVersion,
} from "./protocol";
